FROM amazon/aws-glue-libs:glue_libs_1.0.0_image_01

RUN wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/2.8.5/hadoop-aws-2.8.5.jar -P /home/spark-2.4.3-bin-spark-2.4.3-bin-hadoop2.8/jars/